# Generated by Django 4.2.2 on 2023-12-31 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Contact.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Service.', max_length=50)),
                ('description', models.CharField(help_text="The Service's description.", max_length=100)),
                ('price', models.IntegerField(help_text="The Service's price.")),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('MAP', 'Map'), ('ADDRESS', 'Address')], max_length=20, verbose_name='The choice of the service')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
            ],
        ),
    ]
