# Generated by Django 4.2.2 on 2024-01-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_image_url_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='working_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='working_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='The name of the Contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='choice',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('ADDRESS', 'Address'), ('WORKING_HOURS', 'Working Hours')], max_length=20, verbose_name='The choice of the service'),
        ),
    ]
