# Generated by Django 4.2.2 on 2024-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_address_contact_email_contact_phone_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Advantage', max_length=50)),
                ('description', models.TextField(help_text="The Advantage's description.", max_length=50)),
            ],
        ),
    ]
