# Generated by Django 4.2.2 on 2024-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='image_url',
            field=models.URLField(default='default-image.jpg', help_text="URL of the Service's image"),
        ),
    ]
